<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.

 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>System version information</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Information about the edition of your web application, the Framework, the Control Panel and the system as a whole.</p>
    <p>Information can be obtained from:</p>
    <ul>
        <li>web application configuration panel;</li>
        <li>partition bar "Guide".</li>
    </ul>
</article>